name: ci
on:
  push:
    branches:
      - main
    paths:
      - 'kustomize/**'
      - '.github/workflows/kustomize-build-ci.yaml'
  pull_request:
    paths:
      - 'kustomize/**'
      - '.github/workflows/kustomize-build-ci.yaml'
jobs:
  kustomize:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: kustomize build each component
        run: |
          cd bundles/
          BUNDLES=$(ls -d */)
          for bundle in $BUNDLES;
          do
              echo "## kustomize build for " + $bundle
              kustomize build $bundle
          done
      - name: kustomize build all
        run: |
          cd bundles/
          kustomize build .
  kpt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/setup-gcloud@v0.6.0
      - name: install kpt	
        run: |
          gcloud components install kpt --quiet
      - name: gatekeeper
        run: |
          cd bundles/asm-policy-v0.0.1/
          kpt fn render . --truncate-output=false
