name: ci
on:
  push:
    branches:
      - main
    paths:
      - 'bundles/**'
      - '.github/workflows/ci.yaml'
  pull_request:
    paths:
      - 'bundles/**'
      - '.github/workflows/ci.yaml'
jobs:
  kustomize:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: kustomize build for each component
        run: |
          cd bundles/
          BUNDLES=$(ls -d */)
          for bundle in $BUNDLES;
          do
              echo "## kustomize build for " + $bundle
              kustomize build $bundle
          done
      - name: kustomize build all
        run: |
          cd bundles/
          kustomize build .
  kpt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install kpt
        run: |
          curl -L https://github.com/GoogleContainerTools/kpt/releases/download/v${KPT_VERSION}/kpt_linux_amd64 > kpt
          chmod +x kpt
        env:
          KPT_VERSION: 1.0.0-beta.21
      - name: kpt fn render for each component
        run: |
          cd bundles/
          BUNDLES=$(ls -d */)
          for bundle in $BUNDLES;
          do
              echo "## kpt fn render for " + $bundle
              ../kpt fn render $bundle --truncate-output=false
          done
      - name: create kind cluster
        run: |
          kind create cluster
      - name: kpt live apply for each component
        run: |
          cd bundles/
          BUNDLES=$(ls -d */)
          for bundle in $BUNDLES;
          do
              echo "## kpt live apply for " + $bundle
              ../kpt live apply $bundle --truncate-output=false --dry-run=true --install-resource-group=true
          done
