name: kustomize-build-ci
on:
  push:
    branches:
      - main
    paths:
      - 'kustomize/**'
      - '.github/workflows/kustomize-build-ci.yaml'
  pull_request:
    paths:
      - 'kustomize/**'
      - '.github/workflows/kustomize-build-ci.yaml'
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: kustomize build each component
        run: |
          cd bundles/
          BUNDLES=$(ls .)
          for bundle in $BUNDLES;
          do
              echo "## kustomize build for " + $bundle
              kustomize build $bundle
          done
      - name: kustomize build all
        run: |
          cd bundles/
          kustomize build .
