name: kustomize-build-ci
on:
  push:
    branches:
      - main
    paths:
      - 'kustomize/**'
      - '.github/workflows/kustomize-build-ci.yaml'
  pull_request:
    paths:
      - 'kustomize/**'
      - '.github/workflows/kustomize-build-ci.yaml'
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: kustomize build base
        run: |
          cd bundles/asm-policy-v0.0.1/
          kubectl kustomize .
